/*
 * @(#)BoxTest.java
 * Quaqua Look and Feel. Copyright © 2020 Werner Randelshofer, Switzerland. MIT License.
 */
package test;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.border.TitledBorder;

/**
 * Box test.
 *
 * @author Werner Randelshofer
 * @version $Id$
 */
public class BoxTest extends javax.swing.JPanel {

    /**
     * Creates new form BoxTest
     */
    public BoxTest() {
        initComponents();

        Box box = new Box(BoxLayout.Y_AXIS);
        box.setBorder(new TitledBorder("Ångström"));
        box.add(new JButton("Ångström"));
        add(box);
    }

    public static void main(String[] args) {

        JFrame f = new JFrame("Box Test");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.getContentPane().add(new BoxTest());
        f.pack();
        f.setVisible(true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
