/*
 * @(#)TexturedFrameTest.java
 * Quaqua Look and Feel. Copyright © 2020 Werner Randelshofer, Switzerland. MIT License.
 */

package test;

import javax.swing.*;

/**
 * TexturedFrameTest.
 *
 * @author Werner Randelshofer
 * @version 1.0 2009-09-29 Created.
 */
public class TexturedFrameTest extends javax.swing.JFrame {

    /** Creates new form TexturedFrameTest */
    public TexturedFrameTest() {
        getRootPane().putClientProperty("apple.awt.brushMetalLook", Boolean.TRUE);
       ((JComponent) getContentPane()).setOpaque(true);
        setSize(300,200);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * /
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws Exception {
        UIManager.setLookAndFeel("ch.randelshofer.quaqua.QuaquaLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TexturedFrameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
