/*
 * @(#)ListTest.java
 * Quaqua Look and Feel. Copyright © 2020 Werner Randelshofer, Switzerland. MIT License.
 */

package test;

import ch.randelshofer.quaqua.QuaquaManager;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import static ch.randelshofer.quaqua.QuaquaClientProperties.QUAQUA_LIST_STYLE_CLIENT_PROPERTY;

/**
 * ListTest.
 *
 * @author Werner Randelshofer
 * @version 1.0  13 February 2005  Created.
 */
public class ListTest extends javax.swing.JPanel {

    protected static final String LAYOUT_ORIENTATION_CLIENT_PROPERTY = "layoutOrientation";

    /**
     * Creates new form.
     */
    public ListTest() {
        initComponents();
        stripedList.putClientProperty(QUAQUA_LIST_STYLE_CLIENT_PROPERTY, "striped");

        disabledList.setEnabled(false);
        disabledList.setSelectedIndex(1);
        verticalRadio.putClientProperty(LAYOUT_ORIENTATION_CLIENT_PROPERTY, JList.VERTICAL);
        hwrapRadio.putClientProperty(LAYOUT_ORIENTATION_CLIENT_PROPERTY, JList.HORIZONTAL_WRAP);
        vwrapRadio.putClientProperty(LAYOUT_ORIENTATION_CLIENT_PROPERTY, JList.VERTICAL_WRAP);

        list.setVisibleRowCount(0);
        stripedList.setVisibleRowCount(0);
        disabledList.setVisibleRowCount(0);
        updateLists();

        ItemListener l = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateLists();
            }
        };

        enabledDragOption.addItemListener(l);
        multipleSelectionOption.addItemListener(l);
    }

    private void updateLists() {
        list.setDragEnabled(enabledDragOption.isSelected());
        stripedList.setDragEnabled(enabledDragOption.isSelected());
        disabledList.setDragEnabled(enabledDragOption.isSelected());
        list.setSelectionMode(multipleSelectionOption.isSelected() ? ListSelectionModel.MULTIPLE_INTERVAL_SELECTION : ListSelectionModel.SINGLE_SELECTION);
        stripedList.setSelectionMode(multipleSelectionOption.isSelected() ? ListSelectionModel.MULTIPLE_INTERVAL_SELECTION : ListSelectionModel.SINGLE_SELECTION);
        disabledList.setSelectionMode(multipleSelectionOption.isSelected() ? ListSelectionModel.MULTIPLE_INTERVAL_SELECTION : ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(QuaquaManager.getLookAndFeelClassName());
                } catch (Exception e) {
                    e.printStackTrace();
                }

                JFrame f = new JFrame("ListTest");
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.getContentPane().add(new ListTest());
                f.pack();
                f.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        layoutOrientationGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        stripedList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        disabledList = new javax.swing.JList();
        disabled = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        verticalRadio = new javax.swing.JRadioButton();
        hwrapRadio = new javax.swing.JRadioButton();
        vwrapRadio = new javax.swing.JRadioButton();
        multipleSelectionOption = new javax.swing.JCheckBox();
        enabledDragOption = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 17, 17, 17));
        setLayout(new java.awt.GridBagLayout());

        list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Apple", "Banana", "Cantaloupe", "Cherry", "Grape", "Lemon", "Mango", "Melon", "Orange", "Peach", "Pear", "Pineapple", "Plum", "Strawberry"};

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane2.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane2, gridBagConstraints);

        jLabel5.setText("Plain Style");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        add(jSeparator10, gridBagConstraints);

        stripedList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Agnolotti", "Bavette", "Cannelloni", "Cappellini", "Conchiglie", "Ditalini", "Eliche", "Farfalle", "Fettuccine", "Fusilli", "Garganelli", "Gnocchi", "Lasagne", "Linguine", "Macaroni", "Orecchiette", "Orzo", "Panzarotti", "Pappardelle", "Penne", "Pizzoccheri", "Ravioli", "Rigatoni", "Spaghetti", "Tagliattelle", "Tortellini", "Trenette", "Vermicelli", "Ziti"};

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane8.setViewportView(stripedList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane8, gridBagConstraints);

        jLabel6.setText("Striped Style");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        add(jSeparator11, gridBagConstraints);

        disabledList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Bari", "Biga", "Buccellato", "Bruschetta", "Ciabatta", "Calzone", "Casatiello", "Ciriola", "Farinata", "Focaccia", "Grissini", "Muffuletta", "Pane", "Pandoro", "Panettone", "Panino", "Penia", "Piadina", "Pita", "Pizza", "Rosetta", "Taralli", "Tortano"};

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane9.setViewportView(disabledList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane9, gridBagConstraints);

        disabled.setText("Disabled");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(disabled, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        add(jSeparator1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        layoutOrientationGroup.add(verticalRadio);
        verticalRadio.setSelected(true);
        verticalRadio.setText("Vertical");
        verticalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutOrientationRadioPerformed(evt);
            }
        });
        jPanel1.add(verticalRadio);

        layoutOrientationGroup.add(hwrapRadio);
        hwrapRadio.setText("Horizontal Wrap");
        hwrapRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutOrientationRadioPerformed(evt);
            }
        });
        jPanel1.add(hwrapRadio);

        layoutOrientationGroup.add(vwrapRadio);
        vwrapRadio.setText("Vertical Wrap");
        vwrapRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutOrientationRadioPerformed(evt);
            }
        });
        jPanel1.add(vwrapRadio);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints);

        multipleSelectionOption.setSelected(true);
        multipleSelectionOption.setText("Multiple Selection");
        add(multipleSelectionOption, new java.awt.GridBagConstraints());

        enabledDragOption.setText("Enable drag");
        add(enabledDragOption, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void layoutOrientationRadioPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layoutOrientationRadioPerformed
        int lo = (Integer) ((JComponent) evt.getSource()).getClientProperty(LAYOUT_ORIENTATION_CLIENT_PROPERTY);
        stripedList.setLayoutOrientation(lo);
        disabledList.setLayoutOrientation(lo);
        list.setLayoutOrientation(lo);
    }//GEN-LAST:event_layoutOrientationRadioPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disabled;
    private javax.swing.JList disabledList;
    private javax.swing.JCheckBox enabledDragOption;
    private javax.swing.JRadioButton hwrapRadio;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.ButtonGroup layoutOrientationGroup;
    private javax.swing.JList list;
    private javax.swing.JCheckBox multipleSelectionOption;
    private javax.swing.JList stripedList;
    private javax.swing.JRadioButton verticalRadio;
    private javax.swing.JRadioButton vwrapRadio;
    // End of variables declaration//GEN-END:variables

}
